### ISSUE TITLE
Wrong URL if in Userdir

### ISSUE THREAD

**Issue by rompcik** [bolt/labels#2]
Running in Userdir with main URL like that: http://localhost/~myuser/subdir/ the extension produces wrong administrative urls. Instead of linking to http://localhost/~myuser/subdir/bolt/translation the generated link is http://localhost/bolt/translation.

Complete Userdir and Subdir-parts are missing.

[Subject mistyped: Wring -> Wrong]

**Comment by bobdenotter** [comment]
There's a brand new version 2.0 of this extension. Please try it out, and open a new issue, if problems persist. :-)

**Comment by rompcik** [comment]
Thx. But got a Composer Error installing 2.0. Will open a new issue.

**Comment by GwendolenLynch** [comment]
Satis only finished updating a minute ago… please try now.

**Comment by rompcik** [comment]
The wrong URL seems not to be a specific bug of labels, but from addMenuOption(), see https://github.com/bolt/bolt/issues/4322
