### ISSUE TITLE
No route found for "GET /bolt/labels"

### ISSUE THREAD

**Issue by jan-t3000** [bolt/labels#20]
Hey,

I set up a clean and fresh installation of latest bolt (2.2.13), and installed bolt/labels extension (tried 2.0.5 and dev-master) via backend.
However, with everything untouched, unmodified and out-of-the-box it sais 'No route found for "GET /bolt/labels"'.

Did I miss something? Please help!

Thanks in advance!

**Comment by bobdenotter** [comment]
I've done the same, and no problems for me: 

![screen shot 2015-11-23 at 17 24 34](https://cloud.githubusercontent.com/assets/1833361/11342333/1f73ed54-9207-11e5-919b-e0f04969f84b.png)

I think i did the same: last stable 2.2.13, downloaded from the site. installed 2.05 of labels. And it works. 

Can you give me some more details about what your setup looks like: 
- Apache / nginx
- Mysql / sqlite? 
- which version of PHP?
- installed from tarball or differently? 
- Can i get a _full_ screenshot of the error? 
- Does Bolt work apart from that issue?

**Comment by jan-t3000** [comment]
The Server is Apache, using MySql, php is version 5.6.15 ... I installed bolt the 'traditional' way via FTP upload. Everything else works flawlessly! =/

**Comment by SvanteRichter** [comment]
Just to clarify why this was closed (for any future puzzled issue-nauts), it was fixed in #21.
