### ISSUE TITLE
Adding non english characters wipes translation JSON file

### ISSUE THREAD

**Issue by zomars** [bolt/labels#24]
I'm trying to build a multilingual site which it's default language is spanish, but whenever I try to a add an accented character (á, é, í, ó, ú, etc.). It clears my JSON file completely. 
Here's an example, this code:

```
{{ ('haz reservación') }}
```

renders like this:

```
<mark>haz reservación</mark>
```

Any guidance with this would be deeply appreciated.

**Comment by SvanteRichter** [comment]
Yeah, I noticed the same for swedish charachters (å, ä, ö). This is because it uses strtolower instead of mb_strtolower. I submitted a PR earlier today to fix it: #23

**Comment by GwendolenLynch** [comment]
Fixed in 2.0.7 (just tagged now) :grin:
