### ISSUE TITLE
Faulty link in backend when working in a /en directory

### ISSUE THREAD

**Issue by evertalbers** [bolt/labels#26]
I am using the labels extension in a site in a separate Bolt installation in a `myproject.com/en` directory. 

When I want to edit the labels, the menu in the backend directs me to `myproject.com/bolt/labels` instead of the correct `myproject.com/en/bolt/labels` 

Manually changing the url actually works, luckily. Is probably an easy fix.

**Comment by bobdenotter** [comment]
Fixed in #31.
