### ISSUE TITLE
impossible to set permissions 

### ISSUE THREAD

**Issue by jimi75** [bolt/labels#34]
In Global permissions tried:

labels:
extensions:labels
extend:labels
and many more with no luck

bolt: 3.1.0
bolt/labels: 3.0.2

**Comment by SvanteRichter** [comment]
IIRC in 2.2 there was a custom permission called `labels`, but I'm not sure that is around anymore.

**Comment by jimi75** [comment]
@SahAssar `labels` is not working in bolt: 3.1.0 and bolt/labels: 3.0.2

I tried just for check delete the conditional in `line 73` of file `/extensions/vendor/bolt/labels/src/Controller/Backend.php`

```
        if ($app['permissions']->isAllowed('labels', $user)) {
            return null;
        }
```

Only root users have permission to labels.

**Comment by GwendolenLynch** [comment]
@jimi75 Yep, and you _should_ be just able to add `labels: [ editor ]` in the `global:`  section [here](https://github.com/bolt/bolt/blob/release/3.1/app/config/permissions.yml.dist#L62)

**Comment by jimi75** [comment]
@GawainLynch  i already try that and is not working.

**Comment by jimi75** [comment]
#35
