### ISSUE TITLE
No error when uploading a wrong(?) csv file.

### ISSUE THREAD

**Issue by ankedsgn** [bolt/labels#5]
My Excel for mac saves the default 'csv' option, as a semicolon (;) delimited file. When I try to upload this, I get no reaction at all from the uploader.

Preferred behaviour -> See that this is also a valid csv and import it anyway, with 'succes' message
Alternative behaviour -> Display a valid error message 'something is wrong with your file. Upload failed'

**Comment by bobdenotter** [comment]
There's a brand new version 2.0 of this extension. Please try it out, and open a new issue, if problems persist. :-)
