### ISSUE TITLE
Problem with create MenuEntry on Bolt 3.3.6

### ISSUE THREAD

**Issue by margot-vogo** [bolt/labels#55]
After install Labels on Bolt 3.3.6 coming fatal error.
Solution - change function registerMenuEntries in LabelsExtension.php:

        $menu = new MenuEntry('labels', 'labels');
        $menu->setLabel('Label translations')
            ->setIcon('fa:flag')
            ->setPermission('labels')
        ;

        return [
            $menu,
        ];

**Comment by bobdenotter** [comment]
Sorry! Fixed in #56. Version 3.1.1 includes this fix.
