### ISSUE TITLE
Provide a good manual in the readme

### ISSUE THREAD

**Issue by ankedsgn** [bolt/labels#6]
The readme is pretty.. ehm... obscure. 
It only tells you what tag to use, the rest is probably something you should guess.
I can image the following explanation:
- What tag
- What can you add in the config, if any?
- When is the label added? (a: when the page is loaded)
- What do you do next? (a: download the csv)
- What should you do with the csv?
- What errors can you expect and how to fix this easily

**Comment by phpetra** [comment]
I agree :(

In the official docs you mention this extension as helpful for a multilingual site, but I don't even know what I'm supposed to put in this csv, I apparently need to upload?
What structure should it have? 
And how or where do I define the labels??

Can we maybe have a follow up on this?

**Comment by ankedsgn** [comment]
Hi @bobdenotter, 
could you appoint this issue and all other open issues to someone who can look into them? 
Thanks!

**Comment by GwendolenLynch** [comment]
Throw a penguin at him, @anketwokings :wink:

**Comment by bobdenotter** [comment]
:fire: :boom: :bomb: I'm going to do some light maintenance on this! :fire: :boom: :bomb: :fire: :boom: :bomb: :fire: :boom: :bomb:

**Comment by bobdenotter** [comment]
I made EVERYTHING different! Check the new readme: 

https://github.com/bolt/labels/blob/master/README.md

**Comment by ankedsgn** [comment]
That deserves a penguin! 
_thumbs up!_

**Comment by GwendolenLynch** [comment]
:+1:

**Comment by bobdenotter** [comment]
Fixed by #7

**Comment by phpetra** [comment]
@bobdenotter  Now that is very helpful! 
A big thumbs up from me too!
