### ISSUE TITLE
Composer Error installing Version 2.0

### ISSUE THREAD

**Issue by rompcik** [bolt/labels#8]
Trying to install the new version 2.0 I got a Composer error:

> Composer Error
>  Loading composer repositories with package information
>  Updating dependencies
>  Your requirements could not be resolved to an installable set of packages.
> 
>  Problem 1
>     - The requested package bolt/labels could not be found in any version, there may be a typo in the package name.
> 
> Potential causes:
> - A typo in the package name
> - The package is not available in a stable-enough version according to your minimum-stability setting
>   see this link for more details.
> 
> Read this link for further common problems.

**Comment by GwendolenLynch** [comment]
Derp… I wasn't quick enough… As mentioned in #2 Satis only finished updating a minute ago… please try now. :grin:

**Comment by bobdenotter** [comment]
I had no trouble installing it just now. You might've been too quick to install it after I tagged the new version :-)

Could you try again in a few minutes? 

Edit: *shakes fist at gawain*

**Comment by rompcik** [comment]
Works now. Thx.
